// @generated automatically by Diesel CLI.

diesel::table! {
	/// Representation of the `column_definitions` table.
	///
	/// (Automatically generated by Diesel.)
	column_definitions (id) {
		/// The `id` column of the `column_definitions` table.
		///
		/// Its SQL type is `Integer`.
		///
		/// (Automatically generated by Diesel.)
		id -> Integer,
		/// The `name` column of the `column_definitions` table.
		///
		/// Its SQL type is `Text`.
		///
		/// (Automatically generated by Diesel.)
		name -> Text,
	}
}

diesel::table! {
	/// Representation of the `device_components` table.
	///
	/// (Automatically generated by Diesel.)
	device_components (id) {
		/// The `id` column of the `device_components` table.
		///
		/// Its SQL type is `Integer`.
		///
		/// (Automatically generated by Diesel.)
		id -> Integer,
		/// The `device_key_info_id` column of the `device_components` table.
		///
		/// Its SQL type is `Integer`.
		///
		/// (Automatically generated by Diesel.)
		device_key_info_id -> Integer,
		/// The `component_id` column of the `device_components` table.
		///
		/// Its SQL type is `Text`.
		///
		/// (Automatically generated by Diesel.)
		component_id -> Text,
		/// The `component_type` column of the `device_components` table.
		///
		/// Its SQL type is `Text`.
		///
		/// (Automatically generated by Diesel.)
		component_type -> Text,
	}
}

diesel::table! {
	/// Representation of the `device_data` table.
	///
	/// (Automatically generated by Diesel.)
	device_data (id) {
		/// The `id` column of the `device_data` table.
		///
		/// Its SQL type is `Integer`.
		///
		/// (Automatically generated by Diesel.)
		id -> Integer,
		/// The `device_key_info_id` column of the `device_data` table.
		///
		/// Its SQL type is `Integer`.
		///
		/// (Automatically generated by Diesel.)
		device_key_info_id -> Integer,
		/// The `column_definition_id` column of the `device_data` table.
		///
		/// Its SQL type is `Integer`.
		///
		/// (Automatically generated by Diesel.)
		column_definition_id -> Integer,
		/// The `data_value` column of the `device_data` table.
		///
		/// Its SQL type is `Text`.
		///
		/// (Automatically generated by Diesel.)
		data_value -> Text,
	}
}

diesel::table! {
	/// Representation of the `device_key_info` table.
	///
	/// (Automatically generated by Diesel.)
	device_key_info (id) {
		/// The `id` column of the `device_key_info` table.
		///
		/// Its SQL type is `Integer`.
		///
		/// (Automatically generated by Diesel.)
		id -> Integer,
		/// The `device_id` column of the `device_key_info` table.
		///
		/// Its SQL type is `Text`.
		///
		/// (Automatically generated by Diesel.)
		device_id -> Text,
		/// The `location_id` column of the `device_key_info` table.
		///
		/// Its SQL type is `Integer`.
		///
		/// (Automatically generated by Diesel.)
		location_id -> Integer,
		/// The `last_updated` column of the `device_key_info` table.
		///
		/// Its SQL type is `Timestamp`.
		///
		/// (Automatically generated by Diesel.)
		last_updated -> Timestamp,
	}
}

diesel::table! {
	/// Representation of the `locations` table.
	///
	/// (Automatically generated by Diesel.)
	locations (id) {
		/// The `id` column of the `locations` table.
		///
		/// Its SQL type is `Integer`.
		///
		/// (Automatically generated by Diesel.)
		id -> Integer,
		/// The `name` column of the `locations` table.
		///
		/// Its SQL type is `Text`.
		///
		/// (Automatically generated by Diesel.)
		name -> Text,
	}
}

diesel::joinable!(device_components -> device_key_info (device_key_info_id));
diesel::joinable!(device_data -> column_definitions (column_definition_id));
diesel::joinable!(device_data -> device_key_info (device_key_info_id));
diesel::joinable!(device_key_info -> locations (location_id));

diesel::allow_tables_to_appear_in_same_query!(
	column_definitions,
	device_components,
	device_data,
	device_key_info,
	locations,
);
