name: Artifacts

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04 # Required because newer versions of Ubuntu build without support for older versions of glibc.
          - windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install `nightly` Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v1
        with:
          key: artifacts

      - name: Install NPM
        uses: actions/setup-node@v3

      - name: NPM setup dependencies
        working-directory: ./web
        run: npm ci --production

      # Runs `npm run build` internally
      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Fetch Version String
        id: version_string
        uses: andstor/file-reader-action@v1
        with:
          path: "VERSION.txt"

      - name: Prepare Artifacts (Linux)
        if: runner.os == 'Linux'
        run: |
          mkdir ./release &&
          cp ./target/release/pecan ./release/ &&
          cp -r ./web/build ./release/dist &&
          cp ./pecan.example.toml ./release/ &&
          cp ./setup.bash ./release/ &&
          cp ./LICENSE.md ./release/ &&
          cp ./README.md ./release/ &&
          cp ./VERSION.txt ./release/ &&
          chmod +x ./release/pecan &&
          chmod +x ./release/setup.bash

      - name: Prepare Artifacts (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir .\release &&
          copy .\target\release\pecan.exe .\release\ &&
          xcopy .\web\build .\release\dist /S /I &&
          copy .\pecan.example.toml .\release\ &&
          copy .\LICENSE.md .\release\ &&
          copy .\README.md .\release\ &&
          copy .\VERSION.txt .\release\

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pecan-${{ steps.version_string.outputs.contents }}-${{ matrix.os }}
          path: ./release
          if-no-files-found: error
